apiVersion: v1
kind: Secret
metadata:
  name: app-secrets-dev
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:mysql://host.docker.internal:3306/oficina?useSSL=false&allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_USERNAME: "user"
  SPRING_DATASOURCE_PASSWORD: "password"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
  JWT_SECRET: "superchavesecretajwtdepelomenostrintaedoiscaracteres"
  SECURITY_USER_NAME: "admin"
  SECURITY_USER_PASSWORD: "senhasenha"
