apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap-prod
data:
  SPRING_PORT: "8080"
  SPRING_APPLICATION_NAME: "oficina-api-prod"
  SPRING_APPLICATION_VERSION: "${{ env.SPRING_APPLICATION_VERSION }}"

  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"

  SPRING_JPA_SHOW_SQL: "false"
  SPRING_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQLDialect"
  LOG_LEVEL: "INFO"
  SECURITY_LOG_LEVEL: "WARN"
  JWT_LOG_LEVEL: "ERROR"

  JWT_EXPIRATION: "3600"
  SECURITY_USER_ROLES: "ADMIN"
