apiVersion: v1
kind: Secret
metadata:
  name: app-secrets-prod
type: Opaque
data:
  SPRING_DATASOURCE_URL: "${{ env.SPRING_DATASOURCE_URL }}"
  SPRING_DATASOURCE_USERNAME: "${{ env.SPRING_DATASOURCE_USERNAME }}"
  SPRING_DATASOURCE_PASSWORD: "S{{ env.SPRING_DATASOURCE_PASSWORD }}"
  JWT_SECRET: "${{ env.JWT_SECRET }}"
  SECURITY_USER_NAME: "${{ env.SECURITY_USER_NAME }}"
  SECURITY_USER_PASSWORD: "${{ env.SECURITY_USER_PASSWORD }}"