apiVersion: apps/v1
kind: Deployment
metadata:
  name: oficina-api
  labels:
    app: oficina-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oficina-api
  template:
    metadata:
      labels:
        app: oficina-api
    spec:
      imagePullSecrets:
        - name: aws-ecr-secret
      containers:
      - name: app
        image: oficina-api:2.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PASSWORD
          value: "senharedis"
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        envFrom:
        - configMapRef:
            name: "app-configmap-dev"
        - secretRef:
            name: "app-secrets-dev"